### ISSUE TITLE
xd/xd.hpp: No such file or directory #include <xd/xd.hpp>

### ISSUE THREAD

**Issue by JaViLuMa** [bernhardfritz/libxd#6]
I have issues compiling my sketch example from your site. I always get this error thrown at me or when I use your compiling options I get this error:

![Screenshot_7](https://user-images.githubusercontent.com/16469387/61592620-e9c69480-abd5-11e9-9472-02d468e9186b.png)

How can I fix this?

**Comment by bernhardfritz** [comment]
Hi! The errors shown in your case indicate that the libraries libxd.a, libglad.a and libglfw3.a are not found under the directory lib as specified with -Llib. Maybe you cloned libxd but did not compile it?

You have two options working with libxd. You can either compile libxd from source (steps described here: https://bernhardfritz.github.io/libxd/#/compile?id=windows) or download the latest compiled version from here: https://github.com/bernhardfritz/libxd/releases/latest and extract its contents to your project.

**Comment by JaViLuMa** [comment]
This is what my root directory consists of:
![Screenshot_8](https://user-images.githubusercontent.com/16469387/61593925-35813a00-abe6-11e9-80a9-c48e51020f6f.png)

Inside the lib folder is this:
![Screenshot_9](https://user-images.githubusercontent.com/16469387/61593933-4c279100-abe6-11e9-87e8-828206e39298.png)

And again, inside the lib folder is this:
![Screenshot_10](https://user-images.githubusercontent.com/16469387/61593946-6f524080-abe6-11e9-8d6d-746a0b7dd5ff.png)
Should I move the contents from this last lib folder move to the previous one or?

**Comment by bernhardfritz** [comment]
I think the easiest to get started is by downloading the latest precompiled libraries. Since you have windows this would be: https://github.com/bernhardfritz/libxd/releases/download/0.3.2/libxd-0.3.2-win32.zip
Extract this zip to a new directory and copy your sketch.cpp into it.
Your folder structure should look something like this then:
```
.
├── include
│   ├── GLFW
│   ├── KHR
│   ├── cmake
│   ├── doc
│   ├── glad
│   ├── glm
│   ├── stb
│   ├── test
│   ├── util
│   └── xd
├── lib
│   ├── cmake
│   ├── libglad.a
│   ├── libglfw3.a
│   ├── libxd.a
│   └── pkgconfig
└── sketch.cpp
```
To compile your sketch use:
`g++ -std=c++11 sketch.cpp -o sketch -Iinclude -Llib -lxd -lglad -lglfw3 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32`
And then you can execute it with:
`.\sketch.exe`

**Comment by JaViLuMa** [comment]
This is the error I get now:
![Screenshot_11](https://user-images.githubusercontent.com/16469387/61594959-864a6000-abf1-11e9-800d-4df60c609d8e.png)

**Comment by JaViLuMa** [comment]
Could the issue be cause I am using posix instead of win32 in Mingw-w64? I have mingw-w32 and mingw-w32. Does 32 ming work with GLFW or only 64?

**Comment by bernhardfritz** [comment]
The precompiled libraries are compiled with mingw-w64, so I guess they are not compatible with mingw-w32.

If using mingw-w64 is an option for you, please follow the steps described in the troubleshooting section of the quickstart page (https://bernhardfritz.github.io/libxd/#/quickstart?id=troubleshooting-2) and see if this works for you.

If using mingw-w64 is not an option for you, you would have to compile the libraries with mingw-w32 from source yourself. The steps for doing so are described here: https://bernhardfritz.github.io/libxd/#/compile?id=windows

**Comment by JaViLuMa** [comment]
I have ming64 added to my path from before. What does the troubleshooting suggest? To just download it and add it to the path or?

**Comment by JaViLuMa** [comment]
This is the error I get now:
![Screenshot_12](https://user-images.githubusercontent.com/16469387/61658627-09d58100-acc6-11e9-90b0-1ca8fa54d056.png)

**Comment by JaViLuMa** [comment]
I will try compiling them later, after we had tried every option :p

**Comment by bernhardfritz** [comment]
Yes I was suggesting a fresh install of mingw-w64.
I think we are on the right track though :) Somebody had a similar problem before: https://stackoverflow.com/questions/29199720/undefined-reference-to-ms-vsnprintf-when-linking-glfw-statically
The suggested solution is to use mingw-w64.
If nothing else works please also give it a try to compile from source 👍

**Comment by JaViLuMa** [comment]
Above I placed the screenshot of what happens when I use ming64 path. If you don't know how to fix it, I will try compiling since that is my only option left

**Comment by JaViLuMa** [comment]
So I tried compiling by following your steps. At 23% I got an error:
![Screenshot_13](https://user-images.githubusercontent.com/16469387/61713995-1c999580-ad5a-11e9-99d2-d321b8d324ac.png)




Also, it said I have sh.exe inside my path which was weird since I couldn't find it anywhere.

**Comment by bernhardfritz** [comment]
Where are you executing this from? This does not look like normal windows terminal.
It looks different from your previous screenshots at least.
Please use the terminal that comes with windows (cmd) and try the commands again.

**Comment by JaViLuMa** [comment]
It is a git bash. When I tried using cmd to clone, it said git is not recognized as a command.

**Comment by bernhardfritz** [comment]
ok. use git bash to clone, but do the rest in normal cmd.

**Comment by JaViLuMa** [comment]
It compiled successfully now. Will try to compile a sketch

**Comment by JaViLuMa** [comment]
Okay so, it compiled correctly but when I try to run an example it is all grey. It runs but nothing shows up, the whole windows is grey.
![Screenshot_14](https://user-images.githubusercontent.com/16469387/61747431-293fdd00-ad9e-11e9-8cc9-d5750e801d81.png)

And also, I tried creating a sketch from the Quick start menu and I got an error: glm/gtc/constants.hpp: No such file or directory

![Screenshot_15](https://user-images.githubusercontent.com/16469387/61747579-74f28680-ad9e-11e9-87c1-623a7f3528dc.png)

**Comment by bernhardfritz** [comment]
If you really want to compile a sketch.cpp from libxd root directory (not recommended), you could use this command:
g++ -std=c++11 sketch.cpp -o sketch -Iinclude -Ilib\glad\include -Ilib\glm -Ilib\stb\include -Ilib\glfw\include -Lbuild -Lbuild\lib\glfw\src -lxd -lglad -lglfw3 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32

For your own sanity, I would suggest you to rather follow the examples by implementing a CMakeLists.txt file in order to generate a Makefile which makes compiling much easier.

About your gray window. I have a bad feeling about this. This looks like something went wrong during rendering. I remember there was a bug which I was never able to reproduce that involved AMD graphics cards having problems with the shaders used in libxd.

I guess at this point it must be quite frustrating for you, so I would suggest you to do the following. Either check out https://bernhardfritz.github.io/piksel/ which is a revamp of libxd, or switch to one of following well-established alternatives:
* [openFrameworks (C++)](https://openframeworks.cc/)
* [Processing (Java)](https://processing.org/)
* [p5.js (JavaScript)](https://p5js.org/)

**Comment by JaViLuMa** [comment]
It could be the rendering issue since I do have AMD graphics card. 

I am compiling it from the libxd directory since it says like that on your site so I thought it was the best way.

It isn't frustrating as much as it is mind boggling :p will give a shot with Piksel since I see that is also your project.
