### ISSUE TITLE
I have a few questions in regards to this project

### ISSUE THREAD

**Issue by Joe23232** [bernhardfritz/libxd#7]
Hi I have a few questions regarding this project.

- Is this project abandoned?
- How does this project differ to the [Rust's version of processing](https://github.com/rennis250/processing-rs) (other than being used with a different language)? Is your project better by any chance or something?

**Comment by bernhardfritz** [comment]
Hi @Joe23232 

> Is this project abandoned?

Yes, that's right. I am no longer actively maintaining libxd since it has been superseded by https://github.com/bernhardfritz/piksel

piksel is based off of libxd but has a few improvements:
- instanced rendering (far better performance => more fps)
- can be easily compiled to WebAssembly and therefore be rendered in the browser
- signed distance field based font rendering (outlines are less costly, better performance overall)

> How does this project differ to the Rust's version of processing (other than being used with a different language)?

Thanks for bringing this project to my attention, it looks promising and well structured. Back when I was working on libxd, rust was not even a thing. However, given the reputation of rust, I'd probably choose it too if I'd develop something like libxd today. Having said that, if time allows it, I'd really like to get back to graphics programming and since I'm also interested in rust, I might look into creating yet another graphics library based on it some time in the future. If you compare p5.js, piksel and processing-rs you will see, these projects all offer a common API based on processing. However, the implementations are entirely different.

> Is your project better by any chance or something?

I don't know about processing-rs, but in piksel, everything you put in your "draw" method ultimately boils down to a single OpenGL/WebGL draw call which is a huge benefit, performance wise!

If you are interested in a benchmark, I suggest you try to implement the piksel example https://bernhardfritz.github.io/piksel/#/examples/fireworks/fireworks in processing-rs.

**Comment by Joe23232** [comment]
Hey man,

> Yes, that's right. I am no longer actively maintaining libxd since it has been superseded by https://github.com/bernhardfritz/piksel

> piksel is based off of libxd but has a few improvements:

> instanced rendering (far better performance => more fps)
can be easily compiled to WebAssembly and therefore be rendered in the browser
signed distance field based font rendering (outlines are less costly, better performance overall)

Ah I see thanks for letting me know :)

> Thanks for bringing this project to my attention,

No worryies :)

>  it looks promising and well structured. Back when I was working on libxd, rust was not even a thing.

When did you start working on the project if I may ask?

> However, given the reputation of rust, I'd probably choose it too if I'd develop something like libxd today.

Do you prefer Rust over C++?

> Having said that, if time allows it, I'd really like to get back to graphics programming and since I'm also interested in rust, I might look into creating yet another graphics library based on it some time in the future. If you compare p5.js, piksel and processing-rs you will see, these projects all offer a common API based on processing. However, the implementations are entirely different.

Ah I see

> I don't know about processing-rs, but in piksel, everything you put in your "draw" method ultimately boils down to a single OpenGL/WebGL draw call which is a huge benefit, performance wise!

So is WEbGL for websites and it is the website version of OpenGL?

> If you are interested in a benchmark, I suggest you try to implement the piksel example https://bernhardfritz.github.io/piksel/#/examples/fireworks/fireworks in processing-rs.

Thanks mate :)

**Comment by bernhardfritz** [comment]
I don't want to be rude, but this section is supposed to be about libxd issues. Your latest questions seem to be more of a general nature and I am happy to answer them, but I don't think the issue section of libxd is the right place to do so. For this reason I will close this issue now. Feel free to get in touch with me on discord bernhardfritz#9331

**Comment by Joe23232** [comment]
Oh ok thanks I will add you.

**Comment by Joe23232** [comment]
@bernhardfritz Hey I am sorry again I am going off topic but I really can't seem to add you on discord.

![image](https://user-images.githubusercontent.com/34926497/89122366-e284d700-d509-11ea-921f-2cfaacbffa16.png)

**Comment by bernhardfritz** [comment]
add me as friend, then you can dm me

**Comment by Joe23232** [comment]
Sent to you mate :)
