### ISSUE TITLE
compilling error

### ISSUE THREAD

**Issue by Neumann-Valle** [bernhardfritz/libxd#8]
<pre>
1>------ Build started: Project: drawing, Configuration: Debug Win32 ------
1>main.obj : error LNK2019: unresolved external symbol "void __cdecl xd::size(int,int)" (?size@xd@@YAXHH@Z) referenced in function "void __cdecl setup(void)" (?setup@@YAXXZ)
1>main.obj : error LNK2019: unresolved external symbol "void __cdecl xd::rect(float,float,float,float,bool)" (?rect@xd@@YAXMMMM_N@Z) referenced in function "void __cdecl draw(void)" (?draw@@YAXXZ)
1>MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>C:\Users\UTAN\Desktop\cpp\drawing\Debug\drawing.exe : fatal error LNK1120: 3 unresolved externals
1>Done building project "drawing.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

</pre>

Microsoft Visual Studio Community 2019

example:

```c++
#include <xd/xd.hpp>

using namespace xd;

void setup() {
    size(640, 480);
}

void draw() {
    rect(50, 50, 100, 100);
}

void destroy() {

}
```

I have added additional library..  

I am new to C++

thanks.

**Comment by bernhardfritz** [comment]
Hi! libxd cannot be compiled with the compiler that comes with visual studio. you need mingw64. See section "Troubleshooting" of the libxd documentation: https://bernhardfritz.github.io/libxd/#/quickstart?id=troubleshooting-2

**Comment by Neumann-Valle** [comment]
Hi thanks a lot,
I already had mingw64 installed and set in my "path".
advice me of next step in getting this fixed..

**Comment by bernhardfritz** [comment]
I think installing mingw64 and setting up environment variables is not enough. You need to tell visual studio to use mingw64 instead of the default compiler. I do not use visual studio myself but I guess you should be able to find resources for setting up mingw64 with visual studio, online. A quick google search delivered following tutorial: https://visualgdb.com/tutorials/mingw/mingw64/
No guarantees that this will work, but it should at least get you on the right track.

**Comment by Neumann-Valle** [comment]
ok, thanks..

couldn't get it done.. need to learn more first..  went with VSSTUDIO and SDL tutorials.

Merry Christmas
